import React from 'react';
import './PatientWelcome.css';

function PatientWelcome() {
  return (
    <div className="hos-register-container">
      <div className="hos-register-box">
        <h1>eHospital</h1>
        <h3>Welcome</h3>
        <p>You can register 6 members with one mobile number.</p>
        <button className="hos-register-button">Register Member</button>
        
        <div className="hos-note">
          <h3><span className='i' aria-label="note">ℹ️</span> Note</h3>
          <ul>
            <li>Please do not register with multiple mobile numbers for the same individual.</li>
            <li>It is presumed that you have taken consent from the concerned individuals for registering them through your account.</li>
            <li>You may not use another user's account without their permission.</li>
            <li>The slots availability for OPD/tele-consultation is displayed in the search based on the schedule generated by respective hospitals.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default PatientWelcome;
